"""Antithetic ES gradient estimator for a multi-param model.

For each per-sample perturbation E_i:
    g_i = (f(μ + σ E_i) - f(μ - σ E_i)) / (2σ)  · E_i

We average over N samples and return a dict {param_name: gradient tensor}.

For EGGROLL the perturbations are generated by `perturb_sampler` returning
low-rank E for matrix params; for the reference (full-rank Gaussian) it
returns plain N(0, I).
"""
import torch
from tqdm import tqdm

from .perturbation import add_perturbation


def estimate_gradient(
    fitness,
    sigma,
    N,
    batch_size,
    perturb_sampler,
    device,
    desc=None,
    pbar=True,
):
    """Antithetic ES gradient. perturb_sampler(B) -> dict of (B, *shape) tensors."""
    param_shapes = fitness.param_shapes
    totals = {k: torch.zeros(shape, device=device) for k, shape in param_shapes.items()}

    iterator = range(0, N, batch_size)
    if pbar:
        iterator = tqdm(iterator, desc=desc or "ES", leave=False, total=(N + batch_size - 1) // batch_size)

    cur_bs = batch_size
    i = 0
    while i < N:
        bs = min(cur_bs, N - i)
        try:
            E = perturb_sampler(bs)
            params_plus = add_perturbation(fitness.params, E, sigma, sign=+1)
            params_minus = add_perturbation(fitness.params, E, sigma, sign=-1)
            f_plus = fitness.call_batched(params_plus)    # (bs,)
            f_minus = fitness.call_batched(params_minus)  # (bs,)
            coeff = ((f_plus - f_minus) / (2.0 * sigma)).detach()  # (bs,)
            for k in param_shapes:
                # broadcast coeff over the param shape dims
                view = (bs,) + (1,) * len(param_shapes[k])
                totals[k] = totals[k] + (coeff.view(view) * E[k]).sum(dim=0)
            del E, params_plus, params_minus, f_plus, f_minus, coeff
            i += bs
            if pbar:
                iterator.update(1) if False else None  # tqdm already advanced via iterator
        except torch.cuda.OutOfMemoryError:
            torch.cuda.empty_cache()
            cur_bs = max(1, cur_bs // 2)
            print(f"\n[warn] OOM in ES — halving batch_size to {cur_bs}")
            if cur_bs == 1 and bs == 1:
                raise

    return {k: t / N for k, t in totals.items()}


def stack_grads(grad_list):
    """Stack a list of per-trial gradient dicts into one dict of (T, *shape) tensors."""
    out = {}
    for k in grad_list[0]:
        out[k] = torch.stack([g[k] for g in grad_list], dim=0)
    return out


def flatten_grad(g):
    """Concatenate dict of tensors into one flat vector (for Frobenius/norm ops)."""
    return torch.cat([v.reshape(-1) for v in g.values()])


def norm_F(g):
    return float(torch.linalg.norm(flatten_grad(g)).item())


def diff(g1, g2):
    return {k: g1[k] - g2[k] for k in g1}


def mean_grad(g_stack):
    """Mean over trial dim (axis 0)."""
    return {k: v.mean(dim=0) for k, v in g_stack.items()}


def sem_grad(g_stack):
    """Standard error of the mean as a Frobenius-norm scalar."""
    # SEM_F² = sum over all elements of var(across trials) / T
    T = next(iter(g_stack.values())).shape[0]
    var_sum = 0.0
    for v in g_stack.values():
        var_sum += float(v.var(dim=0, unbiased=True).sum().item())
    return (var_sum / T) ** 0.5
